### ISSUE TITLE
Emergency shell

### ISSUE THREAD

**Issue by mbeavitt** [AsahiLinux/u-boot#22]
Hi all,

Aware this is probably not the right place (please redirect me) but I was wondering if anyone knew how to get an emergency root shell from u-boot? Asking for a friend...

**Comment by jannau** [comment]
See https://docs.fedoraproject.org/en-US/fedora-asahi-remix/troubleshooting/#entering-grub and from there you can edit the kernel command line as you like.
U-boot unfortunately misses cursor support. Then easiest way to reach the end of the kernel command line string is pressing `left` once from the start of the next line.

The Fedora [discussion](https://discussion.fedoraproject.org/c/neighbors/asahi/92) board, the [matrix channel](https://matrix.to/#/#asahi:fedoraproject.org) or the [#asahi irc channel](https://asahilinux.org/community/#irc) would be better contact options.

**Comment by mbeavitt** [comment]
You saved my life. I will use those options in future!
